---
apiVersion: v1
data:
  database-url: database_url_here
kind: Secret
metadata:
  name: database-url
type: Opaque
---
apiVersion: v1
data:
  access-token-secret: access_token_here
kind: Secret
metadata:
  name: access-token-secret
type: Opaque
---
apiVersion: v1
data:
  stripe-secret-key: stripe_secret_key
kind: Secret
metadata:
  name: stripe-secret-key
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: mailtrap-credentails
type: Opaque
data:
  mailtrap-user: user_here
  mailtrap-pass: password_here
---
# Below are google_auth_credentails
apiVersion: v1
kind: Secret
metadata:
  name: api-key
type: Opaque
data:
  .secret-file: google-api-key_here
---
apiVersion: v1
kind: Secret
metadata:
  name: google-client-id
type: Opaque
data:
  .secret-file: client_id_here
  
---
apiVersion: v1
kind: Secret
metadata:
  name: google-client-secret
type: Opaque
data:
  .secret-file: client_secret_here
