apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: nodejsapp
    role: rolling-update
  # type: NodePort
  type: LoadBalancer
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8001
    # nodePort: 30002
    
