---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: backend
  # labels:
  #   type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/goku/HDD/stuff/CodeWithHarry/Nextjs/practice/clgproject"
    # path: "/mnt/data"