import type { Metadata,  } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
// import { Provider } from 'react-redux';
// import store from '@/redux/store';
import { ReduxProvider } from '@/redux/provider';
import Auth from '@/components/Auth';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MovieFlex',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='scrollbar'>
      <body className={inter.className} >
        <Auth>
      <ReduxProvider>
        {children}
        </ReduxProvider>
        </Auth>
      </body>
    </html>
  )
}