---
- 
  name: This will docker 
  hosts: DOcean_k8s_cluster
  # hosts: [master,worker1,worker2]
  # hosts: 
  # - master 
  # - worker1
  # - worker2
  become: true
  tasks:
  - name: install Docker 
    ansible.builtin.package:
      name: docker.io
      state: latest
  - name: start docker serivce
    service:
      name: docker
      state: started
      enabled: yes
 
  - name: download k8s gpg
    apt_key:
      state: present
      url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key  
      keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  # - name: echo gpg
  #   # apt_repository:
  #   ansible.builtin.apt_repository:
  #     state: present
  #     url: "https://pkgs.k8s.io/core:/stable:/v1.29/deb"
      # repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb"
      # dest: /etc/apt/sources.list.d/kubernetes.list
    # command: echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
  # - name: update apt
  #   command: apt update