---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clgFrontend
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clgFrontend
  template:
    metadata:
      labels:
        app: clgFrontend
        role: rolling-update
    spec:
      containers:
      - name: myfrontendapp
        image: clg-frontend:v40
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
        env:
          - name: API_KEY
            valueFrom:
                secretKeyRef:
                  name: Google 
                  key: API_KEY
          - name: GOOGLE_CLIENT_ID
            valueFrom:
                secretKeyRef:
                  name: Google 
                  key: GOOGLE_CLIENT_ID
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
                secretKeyRef:
                  name: Google 
                  key: GOOGLE_CLIENT_SECRET
          - name: AGENT_ID
            valueFrom:
                secretKeyRef:
                  name: dialogflow 
                  key: AGENT_ID
          - name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
            valueFrom:
                secretKeyRef:
                  name: stripe 
                  key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%